namespace MainViewModels;

public partial class MainViewModel
{
    public void CreateTopKMLPart(StringBuilder sb, string DocName)
    {
        sb.AppendLine($@"<?xml version=""1.0"" encoding=""UTF-8""?>");
        sb.AppendLine($@"<kml xmlns=""http://www.opengis.net/kml/2.2"" xmlns:gx=""http://www.google.com/kml/ext/2.2"" xmlns:kml=""http://www.opengis.net/kml/2.2"" xmlns:atom=""http://www.w3.org/2005/Atom"">");
        sb.AppendLine($"<Document>");
        sb.AppendLine($"	<name>{DocName}</name>");
        sb.AppendLine($@"	<StyleMap id=""m_ylw-pushpin"">");
        sb.AppendLine($"		<Pair>");
        sb.AppendLine($"			<key>normal</key>");
        sb.AppendLine($"			<styleUrl>#s_ylw-pushpin</styleUrl>");
        sb.AppendLine($"		</Pair>");
        sb.AppendLine($"		<Pair>");
        sb.AppendLine($"			<key>highlight</key>");
        sb.AppendLine($"			<styleUrl>#s_ylw-pushpin_hl</styleUrl>");
        sb.AppendLine($"		</Pair>");
        sb.AppendLine($"	</StyleMap>");
        sb.AppendLine($@"	<Style id=""s_ylw-pushpin"">");
        sb.AppendLine($"		<IconStyle>");
        sb.AppendLine($"			<scale>1.1</scale>");
        sb.AppendLine($"			<Icon>");
        sb.AppendLine($"				<href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>");
        sb.AppendLine($"			</Icon>");
        sb.AppendLine($@"			<hotSpot x=""20"" y=""2"" xunits=""pixels"" yunits=""pixels""/>");
        sb.AppendLine($"		</IconStyle>");
        sb.AppendLine($"		<LineStyle>");
        sb.AppendLine($"			<width>2</width>");
        sb.AppendLine($"		</LineStyle>");
        sb.AppendLine($"		<PolyStyle>");
        sb.AppendLine($"			<color>00ffffff</color>");
        sb.AppendLine($"		</PolyStyle>");
        sb.AppendLine($"	</Style>");
        sb.AppendLine($@"	<Style id=""s_ylw-pushpin_hl"">");
        sb.AppendLine($"		<IconStyle>");
        sb.AppendLine($"			<scale>1.3</scale>");
        sb.AppendLine($"			<Icon>");
        sb.AppendLine($"				<href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>");
        sb.AppendLine($"			</Icon>");
        sb.AppendLine($@"			<hotSpot x=""20"" y=""2"" xunits=""pixels"" yunits=""pixels""/>");
        sb.AppendLine($"		</IconStyle>");
        sb.AppendLine($"		<LineStyle>");
        sb.AppendLine($"			<width>2</width>");
        sb.AppendLine($"		</LineStyle>");
        sb.AppendLine($"		<PolyStyle>");
        sb.AppendLine($"			<color>00ffffff</color>");
        sb.AppendLine($"			<color>00ffffff</color>");
        sb.AppendLine($"		</PolyStyle>");
        sb.AppendLine($"	</Style>");
        sb.AppendLine($@"	<StyleMap id=""m_ylw-pushpin"">");
        sb.AppendLine($"		<Pair>");
        sb.AppendLine($"			<key>normal</key>");
        sb.AppendLine($"			<styleUrl>#s_ylw-pushpin</styleUrl>");
        sb.AppendLine($"		</Pair>");
        sb.AppendLine($"		<Pair>");
        sb.AppendLine($"			<key>highlight</key>");
        sb.AppendLine($"			<key>highlight</key>");
        sb.AppendLine($"			<styleUrl>#s_ylw-pushpin_hl</styleUrl>");
        sb.AppendLine($"		</Pair>");
        sb.AppendLine($"	</StyleMap>");
        sb.AppendLine($@"	<Style id=""s_ylw-pushpin"">");
        sb.AppendLine($"		<IconStyle>");
        sb.AppendLine($"			<scale>0.4</scale>");
        sb.AppendLine($"			<Icon>");
        sb.AppendLine($"				<href>http://maps.google.com/mapfiles/kml/shapes/placemark_circle.png</href>");
        sb.AppendLine($"			</Icon>");
        sb.AppendLine($"		</IconStyle>");
        sb.AppendLine($"		<ListStyle>");
        sb.AppendLine($"		</ListStyle>");
        sb.AppendLine($"	</Style>");
        sb.AppendLine($@"	<Style id=""s_ylw-pushpin_hl"">");
        sb.AppendLine($"		<IconStyle>");
        sb.AppendLine($"			<scale>0.472727</scale>");
        sb.AppendLine($"			<Icon>");
        sb.AppendLine($"				<href>http://maps.google.com/mapfiles/kml/shapes/placemark_circle_highlight.png</href>");
        sb.AppendLine($"			</Icon>");
        sb.AppendLine($"		</IconStyle>");
        sb.AppendLine($"		<ListStyle>");
        sb.AppendLine($"		</ListStyle>");
        sb.AppendLine($"	</Style>");

        sb.AppendLine($@"	<Style id=""C_0"">");
        sb.AppendLine($"		<IconStyle>");
        sb.AppendLine($"			<scale>1.3</scale>");
        sb.AppendLine($"			<Icon>");
        sb.AppendLine($"				<href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>");
        sb.AppendLine($"			</Icon>");
        sb.AppendLine($@"			<hotSpot x=""20"" y=""2"" xunits=""pixels"" yunits=""pixels""/>");
        sb.AppendLine($"		</IconStyle>");
        sb.AppendLine($"		<LabelStyle>");
        sb.AppendLine($"		</LabelStyle>");
        sb.AppendLine($"		<LineStyle>");
        sb.AppendLine($"		</LineStyle>");
        sb.AppendLine($"		<PolyStyle>");
        sb.AppendLine($"			<width>1</width>");
        sb.AppendLine($"		</PolyStyle>");
        sb.AppendLine($"	</Style>");
        sb.AppendLine($@"	<Style id=""C_0_1"">");
        sb.AppendLine($"		<IconStyle>");
        sb.AppendLine($"			<color>ff0000ff</color>");
        sb.AppendLine($"			<scale>1.3</scale>");
        sb.AppendLine($"			<Icon>");
        sb.AppendLine($"				<href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>");
        sb.AppendLine($"			</Icon>");
        sb.AppendLine($@"			<hotSpot x=""20"" y=""2"" xunits=""pixels"" yunits=""pixels""/>");
        sb.AppendLine($"		</IconStyle>");
        sb.AppendLine($"		<LabelStyle>");
        sb.AppendLine($"			<color>ff0000ff</color>");
        sb.AppendLine($"		</LabelStyle>");
        sb.AppendLine($"		<LineStyle>");
        sb.AppendLine($"			<color>ff0000ff</color>");
        sb.AppendLine($"		</LineStyle>");
        sb.AppendLine($"		<PolyStyle>");
        sb.AppendLine($"			<color>ff0000ff</color>");
        sb.AppendLine($"			<width>1</width>");
        sb.AppendLine($"		</PolyStyle>");
        sb.AppendLine($"	</Style>");
        sb.AppendLine($@"	<Style id=""C_0_3"">");
        sb.AppendLine($"		<IconStyle>");
        sb.AppendLine($"			<color>ff0033ff</color>");
        sb.AppendLine($"			<scale>1.3</scale>");
        sb.AppendLine($"			<Icon>");
        sb.AppendLine($"				<href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>");
        sb.AppendLine($"			</Icon>");
        sb.AppendLine($@"			<hotSpot x=""20"" y=""2"" xunits=""pixels"" yunits=""pixels""/>");
        sb.AppendLine($"		</IconStyle>");
        sb.AppendLine($"		<LabelStyle>");
        sb.AppendLine($"			<color>ff0033ff</color>");
        sb.AppendLine($"		</LabelStyle>");
        sb.AppendLine($"		<LineStyle>");
        sb.AppendLine($"			<color>ff0033ff</color>");
        sb.AppendLine($"		</LineStyle>");
        sb.AppendLine($"		<PolyStyle>");
        sb.AppendLine($"			<color>ff0033ff</color>");
        sb.AppendLine($"			<width>1</width>");
        sb.AppendLine($"		</PolyStyle>");
        sb.AppendLine($"	</Style>");
        sb.AppendLine($@"	<Style id=""C_0_5"">");
        sb.AppendLine($"		<IconStyle>");
        sb.AppendLine($"			<color>ff0066ff</color>");
        sb.AppendLine($"			<scale>1.3</scale>");
        sb.AppendLine($"			<Icon>");
        sb.AppendLine($"				<href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>");
        sb.AppendLine($"			</Icon>");
        sb.AppendLine($@"			<hotSpot x=""20"" y=""2"" xunits=""pixels"" yunits=""pixels""/>");
        sb.AppendLine($"		</IconStyle>");
        sb.AppendLine($"		<LabelStyle>");
        sb.AppendLine($"			<color>ff0066ff</color>");
        sb.AppendLine($"		</LabelStyle>");
        sb.AppendLine($"		<LineStyle>");
        sb.AppendLine($"			<color>ff0066ff</color>");
        sb.AppendLine($"		</LineStyle>");
        sb.AppendLine($"		<PolyStyle>");
        sb.AppendLine($"			<color>ff0066ff</color>");
        sb.AppendLine($"			<width>1</width>");
        sb.AppendLine($"		</PolyStyle>");
        sb.AppendLine($"	</Style>");
        sb.AppendLine($@"	<Style id=""C_0_8"">");
        sb.AppendLine($"		<IconStyle>");
        sb.AppendLine($"			<color>ff0099ff</color>");
        sb.AppendLine($"			<scale>1.3</scale>");
        sb.AppendLine($"			<Icon>");
        sb.AppendLine($"				<href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>");
        sb.AppendLine($"			</Icon>");
        sb.AppendLine($@"			<hotSpot x=""20"" y=""2"" xunits=""pixels"" yunits=""pixels""/>");
        sb.AppendLine($"		</IconStyle>");
        sb.AppendLine($"		<LabelStyle>");
        sb.AppendLine($"			<color>ff0099ff</color>");
        sb.AppendLine($"		</LabelStyle>");
        sb.AppendLine($"		<LineStyle>");
        sb.AppendLine($"			<color>ff0099ff</color>");
        sb.AppendLine($"		</LineStyle>");
        sb.AppendLine($"		<PolyStyle>");
        sb.AppendLine($"			<color>ff0099ff</color>");
        sb.AppendLine($"			<width>1</width>");
        sb.AppendLine($"		</PolyStyle>");
        sb.AppendLine($"	</Style>");
        sb.AppendLine($@"	<Style id=""C_1"">");
        sb.AppendLine($"		<IconStyle>");
        sb.AppendLine($"			<color>ff00ccff</color>");
        sb.AppendLine($"			<scale>1.3</scale>");
        sb.AppendLine($"			<Icon>");
        sb.AppendLine($"				<href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>");
        sb.AppendLine($"			</Icon>");
        sb.AppendLine($@"			<hotSpot x=""20"" y=""2"" xunits=""pixels"" yunits=""pixels""/>");
        sb.AppendLine($"		</IconStyle>");
        sb.AppendLine($"		<LabelStyle>");
        sb.AppendLine($"			<color>ff00ccff</color>");
        sb.AppendLine($"		</LabelStyle>");
        sb.AppendLine($"		<LineStyle>");
        sb.AppendLine($"			<color>ff00ccff</color>");
        sb.AppendLine($"		</LineStyle>");
        sb.AppendLine($"		<PolyStyle>");
        sb.AppendLine($"			<color>ff00ccff</color>");
        sb.AppendLine($"			<width>1</width>");
        sb.AppendLine($"		</PolyStyle>");
        sb.AppendLine($"	</Style>");
        sb.AppendLine($@"	<Style id=""C_10"">");
        sb.AppendLine($"		<IconStyle>");
        sb.AppendLine($"			<color>ff00ff33</color>");
        sb.AppendLine($"			<scale>1.3</scale>");
        sb.AppendLine($"			<Icon>");
        sb.AppendLine($"				<href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>");
        sb.AppendLine($"			</Icon>");
        sb.AppendLine($@"			<hotSpot x=""20"" y=""2"" xunits=""pixels"" yunits=""pixels""/>");
        sb.AppendLine($"		</IconStyle>");
        sb.AppendLine($"		<LabelStyle>");
        sb.AppendLine($"			<color>ff00ff33</color>");
        sb.AppendLine($"		</LabelStyle>");
        sb.AppendLine($"		<LineStyle>");
        sb.AppendLine($"			<color>ff00ff33</color>");
        sb.AppendLine($"		</LineStyle>");
        sb.AppendLine($"		<PolyStyle>");
        sb.AppendLine($"			<color>ff00ff33</color>");
        sb.AppendLine($"			<width>1</width>");
        sb.AppendLine($"		</PolyStyle>");
        sb.AppendLine($"	</Style>");
        sb.AppendLine($@"	<Style id=""C_12"">");
        sb.AppendLine($"		<IconStyle>");
        sb.AppendLine($"			<color>ff00ff00</color>");
        sb.AppendLine($"			<scale>1.3</scale>");
        sb.AppendLine($"			<Icon>");
        sb.AppendLine($"				<href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>");
        sb.AppendLine($"			</Icon>");
        sb.AppendLine($@"			<hotSpot x=""20"" y=""2"" xunits=""pixels"" yunits=""pixels""/>");
        sb.AppendLine($"		</IconStyle>");
        sb.AppendLine($"		<LabelStyle>");
        sb.AppendLine($"			<color>ff00ff00</color>");
        sb.AppendLine($"		</LabelStyle>");
        sb.AppendLine($"		<LineStyle>");
        sb.AppendLine($"			<color>ff00ff00</color>");
        sb.AppendLine($"		</LineStyle>");
        sb.AppendLine($"		<PolyStyle>");
        sb.AppendLine($"			<color>ff00ff00</color>");
        sb.AppendLine($"			<width>1</width>");
        sb.AppendLine($"		</PolyStyle>");
        sb.AppendLine($"	</Style>");
        sb.AppendLine($@"	<Style id=""C_15"">");
        sb.AppendLine($"		<IconStyle>");
        sb.AppendLine($"			<color>ff00cc00</color>");
        sb.AppendLine($"			<scale>1.3</scale>");
        sb.AppendLine($"			<Icon>");
        sb.AppendLine($"				<href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>");
        sb.AppendLine($"			</Icon>");
        sb.AppendLine($@"			<hotSpot x=""20"" y=""2"" xunits=""pixels"" yunits=""pixels""/>");
        sb.AppendLine($"		</IconStyle>");
        sb.AppendLine($"		<LabelStyle>");
        sb.AppendLine($"			<color>ff00cc00</color>");
        sb.AppendLine($"		</LabelStyle>");
        sb.AppendLine($"		<LineStyle>");
        sb.AppendLine($"			<color>ff00cc00</color>");
        sb.AppendLine($"		</LineStyle>");
        sb.AppendLine($"		<PolyStyle>");
        sb.AppendLine($"			<color>ff00cc00</color>");
        sb.AppendLine($"			<width>1</width>");
        sb.AppendLine($"		</PolyStyle>");
        sb.AppendLine($"	</Style>");
        sb.AppendLine($@"	<Style id=""C_2"">");
        sb.AppendLine($"		<IconStyle>");
        sb.AppendLine($"			<color>ff00ffff</color>");
        sb.AppendLine($"			<scale>1.3</scale>");
        sb.AppendLine($"			<Icon>");
        sb.AppendLine($"				<href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>");
        sb.AppendLine($"			</Icon>");
        sb.AppendLine($@"			<hotSpot x=""20"" y=""2"" xunits=""pixels"" yunits=""pixels""/>");
        sb.AppendLine($"		</IconStyle>");
        sb.AppendLine($"		<LabelStyle>");
        sb.AppendLine($"			<color>ff00ffff</color>");
        sb.AppendLine($"		</LabelStyle>");
        sb.AppendLine($"		<LineStyle>");
        sb.AppendLine($"			<color>ff00ffff</color>");
        sb.AppendLine($"		</LineStyle>");
        sb.AppendLine($"		<PolyStyle>");
        sb.AppendLine($"			<color>ff00ffff</color>");
        sb.AppendLine($"			<width>1</width>");
        sb.AppendLine($"		</PolyStyle>");
        sb.AppendLine($"	</Style>");
        sb.AppendLine($@"	<Style id=""C_20"">");
        sb.AppendLine($"		<IconStyle>");
        sb.AppendLine($"			<color>ff009900</color>");
        sb.AppendLine($"			<scale>1.3</scale>");
        sb.AppendLine($"			<Icon>");
        sb.AppendLine($"				<href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>");
        sb.AppendLine($"			</Icon>");
        sb.AppendLine($@"			<hotSpot x=""20"" y=""2"" xunits=""pixels"" yunits=""pixels""/>");
        sb.AppendLine($"		</IconStyle>");
        sb.AppendLine($"		<LabelStyle>");
        sb.AppendLine($"			<color>ff009900</color>");
        sb.AppendLine($"		</LabelStyle>");
        sb.AppendLine($"		<LineStyle>");
        sb.AppendLine($"			<color>ff009900</color>");
        sb.AppendLine($"		</LineStyle>");
        sb.AppendLine($"		<PolyStyle>");
        sb.AppendLine($"			<color>ff009900</color>");
        sb.AppendLine($"			<width>1</width>");
        sb.AppendLine($"		</PolyStyle>");
        sb.AppendLine($"	</Style>");
        sb.AppendLine($@"	<Style id=""C_3"">");
        sb.AppendLine($"		<IconStyle>");
        sb.AppendLine($"			<color>ff00ffcc</color>");
        sb.AppendLine($"			<scale>1.3</scale>");
        sb.AppendLine($"			<Icon>");
        sb.AppendLine($"				<href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>");
        sb.AppendLine($"			</Icon>");
        sb.AppendLine($@"			<hotSpot x=""20"" y=""2"" xunits=""pixels"" yunits=""pixels""/>");
        sb.AppendLine($"		</IconStyle>");
        sb.AppendLine($"		<LabelStyle>");
        sb.AppendLine($"			<color>ff00ffcc</color>");
        sb.AppendLine($"		</LabelStyle>");
        sb.AppendLine($"		<LineStyle>");
        sb.AppendLine($"			<color>ff00ffcc</color>");
        sb.AppendLine($"		</LineStyle>");
        sb.AppendLine($"		<PolyStyle>");
        sb.AppendLine($"			<color>ff00ffcc</color>");
        sb.AppendLine($"			<width>1</width>");
        sb.AppendLine($"		</PolyStyle>");
        sb.AppendLine($"	</Style>");
        sb.AppendLine($@"	<Style id=""C_30"">");
        sb.AppendLine($"		<IconStyle>");
        sb.AppendLine($"			<color>ffff0000</color>");
        sb.AppendLine($"			<scale>1.3</scale>");
        sb.AppendLine($"			<Icon>");
        sb.AppendLine($"				<href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>");
        sb.AppendLine($"			</Icon>");
        sb.AppendLine($@"			<hotSpot x=""20"" y=""2"" xunits=""pixels"" yunits=""pixels""/>");
        sb.AppendLine($"		</IconStyle>");
        sb.AppendLine($"		<LabelStyle>");
        sb.AppendLine($"			<color>ffff0000</color>");
        sb.AppendLine($"		</LabelStyle>");
        sb.AppendLine($"		<LineStyle>");
        sb.AppendLine($"			<color>ffff0000</color>");
        sb.AppendLine($"		</LineStyle>");
        sb.AppendLine($"		<PolyStyle>");
        sb.AppendLine($"			<color>ffff0000</color>");
        sb.AppendLine($"			<width>1</width>");
        sb.AppendLine($"		</PolyStyle>");
        sb.AppendLine($"	</Style>");
        sb.AppendLine($@"	<Style id=""C_45"">");
        sb.AppendLine($"		<IconStyle>");
        sb.AppendLine($"			<color>ffff0033</color>");
        sb.AppendLine($"			<scale>1.3</scale>");
        sb.AppendLine($"			<Icon>");
        sb.AppendLine($"				<href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>");
        sb.AppendLine($"			</Icon>");
        sb.AppendLine($@"			<hotSpot x=""20"" y=""2"" xunits=""pixels"" yunits=""pixels""/>");
        sb.AppendLine($"		</IconStyle>");
        sb.AppendLine($"		<LabelStyle>");
        sb.AppendLine($"			<color>ffff0033</color>");
        sb.AppendLine($"		</LabelStyle>");
        sb.AppendLine($"		<LineStyle>");
        sb.AppendLine($"			<color>ffff0033</color>");
        sb.AppendLine($"		</LineStyle>");
        sb.AppendLine($"		<PolyStyle>");
        sb.AppendLine($"			<color>ffff0033</color>");
        sb.AppendLine($"			<width>1</width>");
        sb.AppendLine($"		</PolyStyle>");
        sb.AppendLine($"	</Style>");
        sb.AppendLine($@"	<Style id=""C_5"">");
        sb.AppendLine($"		<IconStyle>");
        sb.AppendLine($"			<color>ff00ff99</color>");
        sb.AppendLine($"			<scale>1.3</scale>");
        sb.AppendLine($"			<Icon>");
        sb.AppendLine($"				<href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>");
        sb.AppendLine($"			</Icon>");
        sb.AppendLine($@"			<hotSpot x=""20"" y=""2"" xunits=""pixels"" yunits=""pixels""/>");
        sb.AppendLine($"		</IconStyle>");
        sb.AppendLine($"		<LabelStyle>");
        sb.AppendLine($"			<color>ff00ff99</color>");
        sb.AppendLine($"		</LabelStyle>");
        sb.AppendLine($"		<LineStyle>");
        sb.AppendLine($"			<color>ff00ff99</color>");
        sb.AppendLine($"		</LineStyle>");
        sb.AppendLine($"		<PolyStyle>");
        sb.AppendLine($"			<color>ff00ff99</color>");
        sb.AppendLine($"			<width>1</width>");
        sb.AppendLine($"		</PolyStyle>");
        sb.AppendLine($"	</Style>");
        sb.AppendLine($@"	<Style id=""C_7"">");
        sb.AppendLine($"		<IconStyle>");
        sb.AppendLine($"			<color>ff00ff66</color>");
        sb.AppendLine($"			<scale>1.3</scale>");
        sb.AppendLine($"			<Icon>");
        sb.AppendLine($"				<href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>");
        sb.AppendLine($"			</Icon>");
        sb.AppendLine($@"			<hotSpot x=""20"" y=""2"" xunits=""pixels"" yunits=""pixels""/>");
        sb.AppendLine($"		</IconStyle>");
        sb.AppendLine($"		<LabelStyle>");
        sb.AppendLine($"			<color>ff00ff66</color>");
        sb.AppendLine($"		</LabelStyle>");
        sb.AppendLine($"		<LineStyle>");
        sb.AppendLine($"			<color>ff00ff66</color>");
        sb.AppendLine($"		</LineStyle>");
        sb.AppendLine($"		<PolyStyle>");
        sb.AppendLine($"			<color>ff00ff66</color>");
        sb.AppendLine($"			<width>1</width>");
        sb.AppendLine($"		</PolyStyle>");
        sb.AppendLine($"	</Style>");
        sb.AppendLine($@"	<Style id=""C_70"">");
        sb.AppendLine($"		<IconStyle>");
        sb.AppendLine($"			<color>ffff0066</color>");
        sb.AppendLine($"			<scale>1.3</scale>");
        sb.AppendLine($"			<Icon>");
        sb.AppendLine($"				<href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>");
        sb.AppendLine($"			</Icon>");
        sb.AppendLine($@"			<hotSpot x=""20"" y=""2"" xunits=""pixels"" yunits=""pixels""/>");
        sb.AppendLine($"		</IconStyle>");
        sb.AppendLine($"		<LabelStyle>");
        sb.AppendLine($"			<color>ffff0066</color>");
        sb.AppendLine($"		</LabelStyle>");
        sb.AppendLine($"		<LineStyle>");
        sb.AppendLine($"			<color>ffff0066</color>");
        sb.AppendLine($"		</LineStyle>");
        sb.AppendLine($"		<PolyStyle>");
        sb.AppendLine($"			<color>ffff0066</color>");
        sb.AppendLine($"			<width>1</width>");
        sb.AppendLine($"		</PolyStyle>");
        sb.AppendLine($"	</Style>");
    }
}
